FROM mcr.microsoft.com/playwright/python:v1.48.0-focal

WORKDIR /app

COPY . .

# Instala as dependências corretas
RUN pip install --upgrade pip && pip install -r backend/requirements.txt

EXPOSE 10000

# Garante que o app seja encontrado dentro da pasta backend
CMD ["gunicorn", "backend.app:app", "--bind", "0.0.0.0:10000"]
